### PR TITLE
Changes $cmd_duration -> $CMD_DURATION.

### LINKED ISSUE #4: "Invalid integer" error
After successful installation using Fisherman I'm getting the following error whenever I try to execute any command:

```
test returned eval errors:
	invalid integer ''
```

### PR DESCRIPTION
**Pull request by mhubig**
Fixes #4

### CODE REVIEW

**Comment by jorgebucaran** [comment]
https://github.com/fisherman/mono/pull/2

**Comment by mhubig** [comment]
OK I see it should be lowercase `$cmd_duration` since 2.7.0!

- https://github.com/fish-shell/fish-shell/commit/18b06f3768d6f964dd2c679aee2e80a21c820fe4#diff-c765a8d6d5ce3af7cfeb650a8cd83823
- https://github.com/fish-shell/fish-shell/issues/4414

But I'm on 2.7.1 installed from homebrew. Now I'm confused ...

**Comment by jorgebucaran** [comment]
Maybe @faho can illuminate this?

**Comment by mhubig** [comment]
If I download the 2.7.1 tarball from github like [brew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fish.rb) does, the CMD_DURATION is uppercase in reader.cpp:

```
$ rg CMD_DURATION                                                                                                                                          
src/reader.cpp
79:#define ENV_CMD_DURATION L"CMD_DURATION"
769:    env_set(ENV_CMD_DURATION, L"0", ENV_UNEXPORT);
1932:    env_set(ENV_CMD_DURATION, buf, ENV_UNEXPORT);
```

**Comment by jorgebucaran** [comment]
@mhubig The proper solution is to create a `get_duration` plugin, and update all plugins using this variable (probably only those also using humanize_duration) that is backward compatible.

If you can't be bothered by that, you could simply add to this PR:

```fish
if test -z "$cmd_duration"
  set cmd_duration $CMD_DURATION
end
```
...**before** the first use of `echo $cmd_duration | humanize_duration`.

**Comment by jorgebucaran** [comment]
@mhubig And by the way, the reason I was not getting the error if because I was using a cached version of `mono`. I just confirmed that cmd_duration _is not set_ on my fish 2.7.1 either.

**Comment by mhubig** [comment]
If I clone fish-shell and `git checkout 2.7.1 -b release-2.7.1`

```
rg CMD_DURATION src/reader.cpp
  79:     #define ENV_CMD_DURATION L"CMD_DURATION"
 769:         env_set(ENV_CMD_DURATION, L"0", ENV_UNEXPORT);
1932:         env_set(ENV_CMD_DURATION, buf, ENV_UNEXPORT);
```

Here are the two last changes of line 79 in `src/reader.cpp`
```
573916e5e (Kurtis Rader 2017-01-06 21:14:29 -0800 79) #define ENV_CMD_DURATION L"CMD_DURATION"
18b06f376 (Aaron Gyes 2017-10-14 08:18:46 -0700 79)   #define ENV_cmd_duration L"cmd_duration"
```
But the last change is only in master:

```
git tag --contains 573916e5e2.5.0
2.5b1
2.6.0
2.6b1
2.7.0
2.7.1
2.7b1
git tag --contains 18b06f376
```

**Comment by faho** [comment]
>OK I see it should be lowercase $cmd_duration since 2.7.0!

No. Look at that commit again - it's not included in any tag.

This is slated for inclusion in 3.0 next month.

>...before set -l duration (echo $CMD_DURATION | humanize_duration) :)

Or you could do `set -l duration (echo "$CMD_DURATION$cmd_duration" | humanize_duration)`.

**Comment by jorgebucaran** [comment]
> Or you could do set -l duration (echo "$CMD_DURATION$cmd_duration" | humanize_duration).

👍

**Comment by jorgebucaran** [comment]
@mhubig 😄🎉🎉

Apologies for the delay!

**Pull request merged**
